name: release
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
    - uses: notlmn/release-with-changelog@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        exclude: '^polish|^bump|^typo'
        commit-template: '- {hash} {title}'
        template: |
          ### Changelog

          {commits}
    - name: Install
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Build
      run: npm run build

    - name: Upload build to hosting environment
      uses: Atyn/Simple-SFTP
      with:
        url: ${{ secrets.SFTP_URL }}
        local-directory: dist/*
